services:
  postgres:
    image: postgres:15
    container_name: megaline_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: megaline_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume_megaline:/var/lib/postgresql/data

  mage_ai:
    image: mageai/mageai:latest
    container_name: megaline_mage
    environment:
      DATABASE_CONNECTION_URL: postgresql://root:root@postgres:5432/megaline_db
    ports:
      - "6789:6789"
    volumes:
      - mage_ai_volume_megaline:/home/src
    depends_on:
      - postgres

volumes:
  postgres_volume_megaline:
  mage_ai_volume_megaline: